import type { ImageRequireSource } from 'react-native';
import type { GrowthStage, Mood } from './types';

// Every entry here is a require() — never an http/data URI — so the map is
// typed as ImageRequireSource (assignable both to RN's <Image source> on
// the app side and to ImageWidgetSource on the widget side), not the wider
// ImageWidgetSource union.
//
// require() paths must be statically analyzable by Metro, so this is a
// plain lookup table — no branching, no dynamic template paths. Shared by
// the widget headless handler and the foreground app so they always agree
// on which image represents a given {stage, mood}.
//
// The 35 files under assets/character/ are procedurally generated by
// scripts/generate-character-art.js, not hand-illustrated — rerun that
// script to retune shapes/colors instead of editing the PNGs directly.
export const CHARACTER_ASSET_MAP: Record<GrowthStage, Record<Mood, ImageRequireSource>> = {
  egg: {
    joyful: require('../assets/character/egg-joyful.png'),
    content: require('../assets/character/egg-content.png'),
    neutral: require('../assets/character/egg-neutral.png'),
    down: require('../assets/character/egg-down.png'),
    lonely: require('../assets/character/egg-lonely.png'),
  },
  newborn: {
    joyful: require('../assets/character/newborn-joyful.png'),
    content: require('../assets/character/newborn-content.png'),
    neutral: require('../assets/character/newborn-neutral.png'),
    down: require('../assets/character/newborn-down.png'),
    lonely: require('../assets/character/newborn-lonely.png'),
  },
  infant: {
    joyful: require('../assets/character/infant-joyful.png'),
    content: require('../assets/character/infant-content.png'),
    neutral: require('../assets/character/infant-neutral.png'),
    down: require('../assets/character/infant-down.png'),
    lonely: require('../assets/character/infant-lonely.png'),
  },
  child: {
    joyful: require('../assets/character/child-joyful.png'),
    content: require('../assets/character/child-content.png'),
    neutral: require('../assets/character/child-neutral.png'),
    down: require('../assets/character/child-down.png'),
    lonely: require('../assets/character/child-lonely.png'),
  },
  adolescent: {
    joyful: require('../assets/character/adolescent-joyful.png'),
    content: require('../assets/character/adolescent-content.png'),
    neutral: require('../assets/character/adolescent-neutral.png'),
    down: require('../assets/character/adolescent-down.png'),
    lonely: require('../assets/character/adolescent-lonely.png'),
  },
  youngAdult: {
    joyful: require('../assets/character/youngAdult-joyful.png'),
    content: require('../assets/character/youngAdult-content.png'),
    neutral: require('../assets/character/youngAdult-neutral.png'),
    down: require('../assets/character/youngAdult-down.png'),
    lonely: require('../assets/character/youngAdult-lonely.png'),
  },
  elder: {
    joyful: require('../assets/character/elder-joyful.png'),
    content: require('../assets/character/elder-content.png'),
    neutral: require('../assets/character/elder-neutral.png'),
    down: require('../assets/character/elder-down.png'),
    lonely: require('../assets/character/elder-lonely.png'),
  },
};
