import type { ImageRequireSource } from 'react-native';
import type { AgeTier } from './ageTier';
import type { GrowthStage, Mood } from './types';

// Every entry here is a require() — never an http/data URI — so the map is
// typed as ImageRequireSource (assignable both to RN's <Image source> on
// the app side and to ImageWidgetSource on the widget side), not the wider
// ImageWidgetSource union.
//
// require() paths must be statically analyzable by Metro, so this is a
// plain lookup table — no branching, no dynamic template paths. Shared by
// the widget headless handler and the foreground app so they always agree
// on which image represents a given {stage, mood}.
//
// The 20 files under assets/character/ (and the 3 under age-accessories/)
// are procedurally generated by scripts/generate-character-art.js, not
// hand-illustrated — rerun that script to retune shapes/colors instead of
// editing the PNGs directly.
export const CHARACTER_ASSET_MAP: Record<GrowthStage, Record<Mood, ImageRequireSource>> = {
  egg: {
    joyful: require('../assets/character/egg-joyful.png'),
    content: require('../assets/character/egg-content.png'),
    neutral: require('../assets/character/egg-neutral.png'),
    down: require('../assets/character/egg-down.png'),
    lonely: require('../assets/character/egg-lonely.png'),
  },
  hatchling: {
    joyful: require('../assets/character/hatchling-joyful.png'),
    content: require('../assets/character/hatchling-content.png'),
    neutral: require('../assets/character/hatchling-neutral.png'),
    down: require('../assets/character/hatchling-down.png'),
    lonely: require('../assets/character/hatchling-lonely.png'),
  },
  juvenile: {
    joyful: require('../assets/character/juvenile-joyful.png'),
    content: require('../assets/character/juvenile-content.png'),
    neutral: require('../assets/character/juvenile-neutral.png'),
    down: require('../assets/character/juvenile-down.png'),
    lonely: require('../assets/character/juvenile-lonely.png'),
  },
  companion: {
    joyful: require('../assets/character/companion-joyful.png'),
    content: require('../assets/character/companion-content.png'),
    neutral: require('../assets/character/companion-neutral.png'),
    down: require('../assets/character/companion-down.png'),
    lonely: require('../assets/character/companion-lonely.png'),
  },
};

// Age-tier accessory overlays only apply visually in the companion stage,
// and only in the app screen (composited live with a plain <Image>) — the
// widget keeps showing stage+mood only, per the plan's v1 widget scope.
export const AGE_ACCESSORY_ASSET_MAP: Partial<Record<AgeTier, ImageRequireSource>> = {
  1: require('../assets/character/age-accessories/tier1.png'),
  2: require('../assets/character/age-accessories/tier2.png'),
  3: require('../assets/character/age-accessories/tier3.png'),
};
